In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import os
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Function to read text data from a file in a directory
def read_text_from_file(file_path):
    with open(file_path, 'r', encoding='latin-1') as file:
        text_data = file.read()
    return text_data


# Define a function for cleaning and preprocessing the text data
def preprocess_text(text):
    # Remove HTML tags
    text = BeautifulSoup(text, "html.parser").get_text()

    # Convert to lowercase
    text = text.lower()

    # Remove non-alphanumeric characters
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    # Tokenize the text into words
    words = word_tokenize(text)

    # Remove stopwords
    words = [word for word in words if word not in stopwords.words('english')]

    # Lemmatize the words
    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word) for word in words]

    # Join the cleaned words back into a single string
    cleaned_text = " ".join(words)

    return cleaned_text


def vectorize_text_to_df(_text):
    # Vectorize the text coming from cleaned text
    # Feature extraction
    vectorizer = TfidfVectorizer()
    features = vectorizer.fit_transform([_text])
    # Create dataframe
    df = pd.DataFrame(features.toarray(), columns=vectorizer.get_feature_names_out())
    # Print the dataframe
    print(df)
    return df

directory = '/content/drive/MyDrive/energyreporttest'
file_list = os.listdir(directory)
dfMain = pd.DataFrame()
for file_name in file_list:
    file_path = os.path.join(directory, file_name)
    # Call web scrapping function
    _scrapped_data = read_text_from_file(file_path)
    _cleaned_text = preprocess_text(_scrapped_data)
    # Call api to summarize clean txt
    dfn = vectorize_text_to_df(_cleaned_text)
    if dfMain is None or dfMain.empty:
        dfMain = dfn.copy()
    dfMain = pd.merge(dfMain, dfn)

dfMain.head()

      00000  0000000000  0000000015  0000000262  0000000299  0000002071  \
0  0.547646    0.003184    0.003184    0.003184    0.003184    0.003184

   0000004731  0000004945  0000007133  0000007364  ...  zvdco04c3fdk  \
0    0.003184    0.003184    0.003184    0.003184  ...      0.003184

        zvh   zvzfk5a      zwr9  zxfeygmkmt0m6n  zxwqyywqwe  zymsbpighs2  \
0  0.003184  0.003184  0.003184        0.003184    0.003184     0.003184

    zzauqvr      zzhj       zzo
0  0.003184  0.003184  0.003184

[1 rows x 1950 columns]
      00000  0000000000  0000000015  0000000262  0000000299  0000002029  \
0  0.548476    0.003407    0.003407    0.003407    0.003407    0.003407

   0000004982  0000005185  0000006950  0000007181  ...      ztjn  ztzcxhxxha  \
0    0.003407    0.003407    0.003407    0.003407  ...  0.003407    0.003407

   zvj0t8cym1sbm  zwellvoji     zxe7f       zxj  zy0unervfgx   zybqkwb  \
0       0.003407   0.003407  0.003407  0.003407     0.003407  0.003407

   zyik5nkhrkx       zzh
0     0.003407  0.003407

[1 rows x 1886 columns]
        00     00000  0000000000  0000000015  0000000262  0000000299  \
0  0.00422  0.548645     0.00422     0.00422     0.00422     0.00422

   0000003156  0000003359  0000005592  0000005823  ...       zr  \
0     0.00422     0.00422     0.00422     0.00422  ...  0.00422

   zsaonpqs2jkjx  ztp6ztxsf     zuhn       zv       zw  zw2l7rr     zwpm  \
0        0.00422    0.00422  0.00422  0.00422  0.00422  0.00422  0.00422

        zx  zygeumfzthsgcngynl4uozrr
0  0.00422                   0.00422

[1 rows x 1711 columns]
      00000  0000000000  0000000015  0000000262  0000000299  0000002078  \
0  0.545564    0.002949    0.002949    0.002949    0.002949    0.002949

   0000004776  0000004974  0000007223  0000007454  ...        zt    zuearm  \
0    0.002949    0.002949    0.002949    0.002949  ...  0.002949  0.002949

   zuiiukuaq7xw  zveaarr2y      zvfi       zvi   zvu56ux  zxivix9hi60hocl2  \
0      0.002949   0.002949  0.002949  0.002949  0.002949          0.002949

         zz       zzu
0  0.002949  0.002949

[1 rows x 2064 columns]
      00000  0000000000  0000000015  0000000262  0000000299  0000002065  \
0  0.551573    0.003363    0.003363    0.003363    0.003363    0.003363

   0000004341  0000005877  0000006075  0000007818  ...  zweyc7dx   zwmw10z  \
0    0.003363    0.003363    0.003363    0.003363  ...  0.003363  0.003363

        zxj        zy  zy6tlendfuz       zyp  zyyeeyhp  zznymideogd0  \
0  0.003363  0.003363     0.003363  0.003363  0.003363      0.003363

   zzunlh9ok69jizfh0  zzw3wjmdjwl4
0           0.003363      0.003363

[1 rows x 1859 columns]
      00000  0000000000  0000000015  0000000262  0000000299  0000002043  \
0  0.550616    0.003164    0.003164    0.003164    0.003164    0.003164

   0000004556  0000004761  0000006895  0000007126  ...     zsbgg      zsmq  \
0    0.003164    0.003164    0.003164    0.003164  ...  0.003164  0.003164

   zssnor0n        zt       zv5      zvlc  zvxjlu3upeuq  zvzpi644jjje7  \
0  0.003164  0.003164  0.003164  0.003164      0.003164       0.003164

      zynvz    zzc5qi
0  0.003164  0.003164

[1 rows x 1849 columns]
      00000  0000000000  0000000015  0000000262  0000000299  0000000375  \
0  0.552983    0.003568    0.003568    0.003568    0.003568    0.003568

   0000003767  0000006923  0000007127  0000008853  ...    zt5tnb     zuijz  \
0    0.003568    0.003568    0.003568    0.003568  ...  0.003568  0.003568

   zulofi5imhgh        zv       zvf       zx3       zxp  zykp3l3ptxw74r4d  \
0      0.003568  0.007135  0.003568  0.003568  0.003568          0.003568

     zyvwnn  zznryymj0whfc
0  0.003568       0.003568

[1 rows x 1946 columns]
     00000  0000000000  0000000015  0000000262  0000000299  0000003287  \
0  0.54613    0.003901    0.003901    0.003901    0.003901    0.003901

   0000003494  0000005811  0000006042  0000006289  ...       zql    zqtalg  \
0    0.003901    0.003901    0.003901    0.003901  ...  0.003901  0.003901

   zrjvpckofrzerd    zszkm3       zvh       zvp    zw6lui   zwp5kau    zy2yie  \
0        0.003901  0.003901  0.003901  0.003901  0.003901  0.003901  0.003901

   zy5p5zyaokyyq
0       0.003901

[1 rows x 1763 columns]
      00000  0000000000  0000000015  0000000262  0000000299  0000002050  \
0  0.550853    0.003421    0.003421    0.003421    0.003421    0.003421

   0000004980  0000005184  0000006918  0000007149  ...     zrizs      zss9  \
0    0.003421    0.003421    0.003421    0.003421  ...  0.003421  0.003421

   ztquplscdqfr6438utt9c  ztsv3y0pcngzvmn        zu  zuvss8zfv9ux4s        zv  \
0               0.003421         0.003421  0.003421        0.003421  0.003421

        zyy  zyzib4luzk  zzmrutvqd
0  0.003421    0.003421   0.003421

[1 rows x 1874 columns]

,00000,0000000000,0000000015,0000000262,0000000299,0000002050,0000004980,0000005184,0000006918,0000007149,...,zrizs,zss9,ztquplscdqfr6438utt9c,ztsv3y0pcngzvmn,zu,zuvss8zfv9ux4s,zv,zyy,zyzib4luzk,zzmrutvqd
0,0.550853,0.003421,0.003421,0.003421,0.003421,0.003421,0.003421,0.003421,0.003421,0.003421,...,0.003421,0.003421,0.003421,0.003421,0.003421,0.003421,0.003421,0.003421,0.003421,0.003421

In [ ]:
# Specify the path and file name for the Excel file
output_file = "output2.xlsx"

# Copy the DataFrame to an Excel file
dfMain.to_excel(output_file)

print("DataFrame copied to Excel file successfully.")